version: '3'

services:
  mysql:
    container_name: todo-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo-mysql
      TZ: "Asia/Tokyo"
    volumes:
      - ./db-data:/var/lib/mysql
      #- ./mysql/my.cnf:/etc/mysql/my.cnf
      #- ./mysql/init/:/docker-entrypoint-initdb.d
  golang:
    links:
      - mysql
    build:
      context: ./golang/
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    volumes:
      - ./golang/:/go/src/work
    environment:
      TZ: "Asia/Tokyo"
    #command: sh ./scripts/start_app.sh
    command: "sleep infinity"
  vue:
    build:
      context: ./vue/
      dockerfile: Dockerfile
    ports:
      - 8888:8080
    volumes:
      - ./vue:/vue
      - /app/node_modules
    command: "sleep infinity"

volumes:
  db-data:
    driver: local